# Generated by Django 2.2.3 on 2019-07-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adquired_albums',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/pictures/', verbose_name='Profile image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reputation',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='sold_albums',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
