# Generated by Django 2.2.3 on 2019-07-19 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190719_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time in which the object was created', verbose_name='Created at field')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time in which the object was modified', verbose_name='Modified at field')),
                ('rating', models.FloatField(default=1.0)),
                ('comments', models.TextField(blank=True)),
                ('rated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rated_user', to=settings.AUTH_USER_MODEL)),
                ('rating_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-modified_at', '-rating'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
