# Generated by Django 2.2.3 on 2019-07-21 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumrating',
            old_name='rated_song',
            new_name='rated_album',
        ),
    ]
