# Generated by Django 2.2.3 on 2019-07-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0003_auto_20190721_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='quantities',
        ),
    ]
