# Generated by Django 2.2.3 on 2019-07-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0004_remove_album_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
