# Generated by Django 2.2.3 on 2019-07-22 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0006_auto_20190722_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='sold_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_sold_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
